backend:
  name: github
  repo: KaneriMio/kaneri-mio-lowadi
  branch: main
  base_url: https://vercel.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "coats"
    label: "Окрасы Lowadi"

    files:
      - label: "База окрасов"
        name: "database"
        file: "database.json"

        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Название", name: "name", widget: "string" }
          - { label: "Автор", name: "author", widget: "string" }

  - name: "items"
    label: "Предметы"

    files:
      - label: "База предметов"
        name: "items"
        file: "items.json"

        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Название", name: "name", widget: "string" }