backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "coats"
    label: "Окрасы Lowadi"
    file: "database.json"
    format: "json"

    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Название", name: "name", widget: "string" }
      - { label: "Автор", name: "author", widget: "string" }

  - name: "items"
    label: "Предметы"
    file: "items.json"
    format: "json"

    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Название", name: "name", widget: "string" }